language: python
sudo: required
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - libpcap-dev
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pcapy
  - python setup.py build
  - python setup.py install
# command to run tests
script: "python setup.py test"

